version: "3.8"

services:
  back:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    entrypoint: .docker/backend/entrypoint.sh
    volumes:
      - static_volume:/code/book_review/static
      - media_volume:/code/book_review/media
      - logs_volume:/code/book_review/logs
      - ./:/code/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    restart: unless-stopped
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./.env
  redis:
    restart: unless-stopped
    image: redis:7.0.4
    command: --port 6379
    expose:
      - 6379
  nginx:
    restart: unless-stopped
    build:
      context: .docker/nginx/
      dockerfile: Dockerfile
      args:
        - ENV=dev
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - back
volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
