# Generated by Django 4.1.3 on 2022-11-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="rate",
            new_name="rating",
        ),
    ]
